### PR TITLE
Proposed changes to StEvent module to deal with PXL local coordinates conversion

### PR DESCRIPTION
**Pull request by plexoos**
This is a request to push a few changes to the master branch. The changes are to take care of not properly initialized class members and other fixes to the StPxlHit class. 

To comment on this pull request please use the inputbox at the bottom of this page. If you comment on individual commits your comments may not be visible if we choose to re-arrange/change the commits on this branch. I think it is absolutely ok to overwrite a short published branch while refining commits instead of multiplying branches.

### CODE REVIEW

**Comment by plexoos** [comment]
Thanks Mustafa!
 
1) + 2) The reason for defining constants in StEvent/ is dectated by one of the design requirements for the StEvent module. That is we want to keep it as independent of other modules as possible, i.e. if we defined the constants in StPxlUtil then effectively StEvent library would depend on StPxlUtil. I don't think it would be a huge problem but keeping the library with persistent objects independent of anything else is not a completely unreasonable thing to do.
I'll have another look at StEnumerations.h to see how many other constants we define there. I am aware only of StIstConsts. But if the number of const definitions is becoming significant it maybe a good idea to move them in, say, StConstants.h for clarity.

3) I am aware of the same constants defined in StPxlUtil/StPxlConstants.h
If this change is approved by Thomas U. and we move the constants to StEvent/ I will  switch to using the new header where applicable and remove the definitions from StPxlConstants.h so we don't have duplicates

4) Ok

**Comment by MustafaMustafa** [comment]
I have several interrelated comments on 6bc291398e43da037aa32409c25bed881edef0d6 :

1) I think this header file is for enumerations it is better to define constants elsewhere. 
2) Many of the already existing IST constants are also defined in StIstUtil/StIstConst.h. Any reason to have them in multiple locations?
3) Two of your added PXL constants are available in StPxlUtil/StPxlConstants.h. 
4) Speaking of HFT constants, can you also add the following to StPxlConstants.h so I can remove them from StPxlISim. 
const Double_t PXL_ACTIVE_X_LENGTH = 1.921;
const Double_t PXL_ACTIVE_Y_LENGTH = 1.9872;
With the appropriate naming style of course.

**Comment by plexoos** [comment]
Thanks Mustafa!

1) + 2) The reason for defining constants in StEvent/ is dictated by one of the design requirements for the StEvent module. That is we want to keep it as independent of other modules as possible, i.e. if we defined the constants in StPxlUtil then effectively StEvent library would depend on StPxlUtil. I don't think it would be a huge problem but keeping the library with persistent objects independent of anything else is not a completely unreasonable thing to do.
I'll have another look at StEnumerations.h to see how many other constants we define there. I am aware only of StIstConsts. But if the number of const definitions is becoming significant it maybe a good idea to move them in, say, StConstants.h for clarity.

3) I am aware of the same constants defined in StPxlUtil/StPxlConstants.h
If this change is approved by Thomas U. and we move the constants to StEvent/ I will switch to using the new header where applicable and remove the definitions from StPxlConstants.h so we don't have duplicates

4) Ok

**Comment by MustafaMustafa** [comment]
I have no further comments on this pull request. I think we can proceed and merge this request.

**Comment by plexoos** [comment]
There seems to be a requirement to not have any constants and new dependencies for the StEvent package. So, I implemented the changes in a different way. See https://github.com/star-bnl/star-stevent/pull/3

**Pull request closed without merging**
